# Explorando dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_hdf("train.h5")

In [3]:
df.head()

,id,timestamp,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_36,technical_37,technical_38,technical_39,technical_40,technical_41,technical_42,technical_43,technical_44,y
0,10,0,0.370326,-0.006316,0.222831,-0.213030,0.729277,-0.335633,0.113292,1.621238,...,0.775208,NaN,NaN,NaN,-0.414776,NaN,NaN,-2.0,NaN,-0.011753
1,11,0,0.014765,-0.038064,-0.017425,0.320652,-0.034134,0.004413,0.114285,-0.210185,...,0.025590,NaN,NaN,NaN,-0.273607,NaN,NaN,-2.0,NaN,-0.001240
2,12,0,-0.010622,-0.050577,3.379575,-0.157525,-0.068550,-0.155937,1.219439,-0.764516,...,0.151881,NaN,NaN,NaN,-0.175710,NaN,NaN,-2.0,NaN,-0.020940
3,25,0,NaN,NaN,NaN,NaN,NaN,0.178495,NaN,-0.007262,...,1.035936,NaN,NaN,NaN,-0.211506,NaN,NaN,-2.0,NaN,-0.015959
4,26,0,0.176693,-0.025284,-0.057680,0.015100,0.180894,0.139445,-0.125687,-0.018707,...,0.630232,NaN,NaN,NaN,-0.001957,NaN,NaN,0.0,NaN,-0.007338

In [4]:
df.shape

(1710756, 111)

In [5]:
sample = df[df.timestamp== 0]

In [6]:
#sample.head()
sample.describe()

/opt/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,id,timestamp,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_36,technical_37,technical_38,technical_39,technical_40,technical_41,technical_42,technical_43,technical_44,y
count,750.000000,750.0,700.000000,647.000000,512.000000,657.000000,559.000000,721.000000,426.000000,588.000000,...,749.000000,0.0,0.0,0.0,749.000000,0.0,0.0,745.000000,0.0,750.000000
mean,1077.598667,0.0,0.039326,0.111925,-0.100055,-0.093836,0.080802,0.023321,0.100177,-0.230497,...,0.079136,NaN,NaN,NaN,-0.009031,NaN,NaN,-1.135571,NaN,-0.001870
std,627.278542,0.0,0.792450,0.423766,3.133464,2.626800,0.581651,0.250926,0.400445,2.906583,...,0.712279,NaN,NaN,NaN,0.405304,NaN,NaN,0.991438,NaN,0.026646
min,10.000000,0.0,-5.951849,-0.065637,-64.273834,-45.507469,-3.117925,-2.344957,-2.503073,-65.772797,...,-1.611520,NaN,NaN,NaN,-0.522915,NaN,NaN,-2.000000,NaN,-0.086094
25%,542.250000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.015321
50%,1080.500000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002888
75%,1623.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.012021
max,2156.000000,0.0,15.981620,6.322214,9.511993,6.586653,4.174034,0.986625,2.777665,3.625143,...,5.387029,NaN,NaN,NaN,1.558775,NaN,NaN,0.000000,NaN,0.091730

In [7]:
print len([i for i in df.columns if "fundamental" in i])
print len([i for i in df.columns if "technical" in i])

63
40

### Porcentaje de celdas null  por columna

In [8]:
print ("NULLS per column")
for col in df.columns:
    nulls = df[col].isnull().sum()
    print("%20s"%col, "%7d"%nulls, "(%5.2f"%(nulls*100./len(df))+"%)")
    
#20 se van 40 fund

NULLS per column
(u'                  id', '      0', '( 0.00%)')
(u'           timestamp', '      0', '( 0.00%)')
(u'           derived_0', '  72959', '( 4.26%)')
(u'           derived_1', '  81029', '( 4.74%)')
(u'           derived_2', ' 398651', '(23.30%)')
(u'           derived_3', ' 149471', '( 8.74%)')
(u'           derived_4', ' 406458', '(23.76%)')
(u'       fundamental_0', '  23947', '( 1.40%)')
(u'       fundamental_1', ' 679070', '(39.69%)')
(u'       fundamental_2', ' 368840', '(21.56%)')
(u'       fundamental_3', ' 454380', '(26.56%)')
(u'       fundamental_5', ' 962020', '(56.23%)')
(u'       fundamental_6', ' 701625', '(41.01%)')
(u'       fundamental_7', '  26340', '( 1.54%)')
(u'       fundamental_8', ' 373166', '(21.81%)')
(u'       fundamental_9', ' 565567', '(33.06%)')
(u'      fundamental_10', ' 112977', '( 6.60%)')
(u'      fundamental_11', ' 368840', '(21.56%)')
(u'      fundamental_12', ' 110871', '( 6.48%)')
(u'      fundamental_13', ' 355138', '(20.76%)')
(u'      fundamental_14', ' 356084', '(20.81%)')
(u'      fundamental_15', ' 354897', '(20.75%)')
(u'      fundamental_16', ' 355138', '(20.76%)')
(u'      fundamental_17', '  97222', '( 5.68%)')
(u'      fundamental_18', '  15833', '( 0.93%)')
(u'      fundamental_19', '  54588', '( 3.19%)')
(u'      fundamental_20', ' 110871', '( 6.48%)')
(u'      fundamental_21', '  54333', '( 3.18%)')
(u'      fundamental_22', ' 558488', '(32.65%)')
(u'      fundamental_23', ' 356723', '(20.85%)')
(u'      fundamental_24', ' 576655', '(33.71%)')
(u'      fundamental_25', ' 121894', '( 7.13%)')
(u'      fundamental_26', ' 657184', '(38.41%)')
(u'      fundamental_27', ' 281298', '(16.44%)')
(u'      fundamental_28', ' 667331', '(39.01%)')
(u'      fundamental_29', ' 354106', '(20.70%)')
(u'      fundamental_30', ' 354907', '(20.75%)')
(u'      fundamental_31', ' 454380', '(26.56%)')
(u'      fundamental_32', ' 111672', '( 6.53%)')
(u'      fundamental_33', '  13835', '( 0.81%)')
(u'      fundamental_34', ' 434862', '(25.42%)')
(u'      fundamental_35', ' 424476', '(24.81%)')
(u'      fundamental_36', '  15843', '( 0.93%)')
(u'      fundamental_37', ' 355843', '(20.80%)')
(u'      fundamental_38', ' 803489', '(46.97%)')
(u'      fundamental_39', ' 377574', '(22.07%)')
(u'      fundamental_40', ' 279702', '(16.35%)')
(u'      fundamental_41', '  30115', '( 1.76%)')
(u'      fundamental_42', '  22913', '( 1.34%)')
(u'      fundamental_43', ' 354531', '(20.72%)')
(u'      fundamental_44', ' 355805', '(20.80%)')
(u'      fundamental_45', '  16062', '( 0.94%)')
(u'      fundamental_46', ' 355843', '(20.80%)')
(u'      fundamental_47', ' 446328', '(26.09%)')
(u'      fundamental_48', '  15843', '( 0.93%)')
(u'      fundamental_49', ' 558333', '(32.64%)')
(u'      fundamental_50', ' 355231', '(20.76%)')
(u'      fundamental_51', ' 447053', '(26.13%)')
(u'      fundamental_52', ' 153927', '( 9.00%)')
(u'      fundamental_53', '  23947', '( 1.40%)')
(u'      fundamental_54', ' 384213', '(22.46%)')
(u'      fundamental_55', ' 368840', '(21.56%)')
(u'      fundamental_56', ' 368840', '(21.56%)')
(u'      fundamental_57', ' 657184', '(38.41%)')
(u'      fundamental_58', ' 142125', '( 8.31%)')
(u'      fundamental_59', '  16062', '( 0.94%)')
(u'      fundamental_60', ' 355126', '(20.76%)')
(u'      fundamental_61', ' 671801', '(39.27%)')
(u'      fundamental_62', ' 112977', '( 6.60%)')
(u'      fundamental_63', ' 375614', '(21.96%)')
(u'         technical_0', '  19165', '( 1.12%)')
(u'         technical_1', ' 126776', '( 7.41%)')
(u'         technical_2', '   4279', '( 0.25%)')
(u'         technical_3', '  98294', '( 5.75%)')
(u'         technical_5', ' 153604', '( 8.98%)')
(u'         technical_6', '   4279', '( 0.25%)')
(u'         technical_7', '   2236', '( 0.13%)')
(u'         technical_9', '  19165', '( 1.12%)')
(u'        technical_10', ' 167483', '( 9.79%)')
(u'        technical_11', '   4279', '( 0.25%)')
(u'        technical_12', '  19165', '( 1.12%)')
(u'        technical_13', '   4764', '( 0.28%)')
(u'        technical_14', '  14184', '( 0.83%)')
(u'        technical_16', '  19981', '( 1.17%)')
(u'        technical_17', '   4279', '( 0.25%)')
(u'        technical_18', '  20016', '( 1.17%)')
(u'        technical_19', '   2320', '( 0.14%)')
(u'        technical_20', '   4764', '( 0.28%)')
(u'        technical_21', '   2236', '( 0.13%)')
(u'        technical_22', '      0', '( 0.00%)')
(u'        technical_24', '  71146', '( 4.16%)')
(u'        technical_25', ' 208056', '(12.16%)')
(u'        technical_27', '   2420', '( 0.14%)')
(u'        technical_28', ' 262916', '(15.37%)')
(u'        technical_29', '  61615', '( 3.60%)')
(u'        technical_30', '   4764', '( 0.28%)')
(u'        technical_31', ' 182678', '(10.68%)')
(u'        technical_32', '  19165', '( 1.12%)')
(u'        technical_33', '  14535', '( 0.85%)')
(u'        technical_34', '      0', '( 0.00%)')
(u'        technical_35', '   3155', '( 0.18%)')
(u'        technical_36', '   2552', '( 0.15%)')
(u'        technical_37', '  19165', '( 1.12%)')
(u'        technical_38', '  19165', '( 1.12%)')
(u'        technical_39', '  20016', '( 1.17%)')
(u'        technical_40', '   2236', '( 0.13%)')
(u'        technical_41', '  44189', '( 2.58%)')
(u'        technical_42', '  20001', '( 1.17%)')
(u'        technical_43', '   4686', '( 0.27%)')
(u'        technical_44', ' 236779', '(13.84%)')
(u'                   y', '      0', '( 0.00%)')

In [9]:
print len(df.id.unique()), len(df.timestamp.unique())

1424 1813

In [10]:
notnull1 = df.dropna(axis=0).shape[0] #no son nan
notnull2 = df.dropna(axis=1).shape[1]

print 100.*(df.shape[0]-notnull1)/df.shape[0] #porcentaje filas con algun nans
print 100.*(df.shape[1]-notnull2)/df.shape[1] #cols  nans

86.9624890984
95.4954954955

In [11]:
#df = df.fillna(df.mean) #se demora mucho
#df.to_hdf("mean.h5")

## Ordenamos por tiempo y reemplazmos nan's por media

In [12]:
df = pd.concat([df.timestamp,df.groupby('timestamp').transform(lambda x: x.fillna(x.mean()))],axis=1) #nope

In [13]:
df.head()

,timestamp,id,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_36,technical_37,technical_38,technical_39,technical_40,technical_41,technical_42,technical_43,technical_44,y
0,0,10,0.370326,-0.006316,0.222831,-0.213030,0.729277,-0.335633,0.113292,1.621238,...,0.775208,NaN,NaN,NaN,-0.414776,NaN,NaN,-2.0,NaN,-0.011753
1,0,11,0.014765,-0.038064,-0.017425,0.320652,-0.034134,0.004413,0.114285,-0.210185,...,0.025590,NaN,NaN,NaN,-0.273607,NaN,NaN,-2.0,NaN,-0.001240
2,0,12,-0.010622,-0.050577,3.379575,-0.157525,-0.068550,-0.155937,1.219439,-0.764516,...,0.151881,NaN,NaN,NaN,-0.175710,NaN,NaN,-2.0,NaN,-0.020940
3,0,25,0.039326,0.111925,-0.100055,-0.093836,0.080802,0.178495,0.100177,-0.007262,...,1.035936,NaN,NaN,NaN,-0.211506,NaN,NaN,-2.0,NaN,-0.015959
4,0,26,0.176693,-0.025284,-0.057680,0.015100,0.180894,0.139445,-0.125687,-0.018707,...,0.630232,NaN,NaN,NaN,-0.001957,NaN,NaN,0.0,NaN,-0.007338

** se eliminan columnas que quedan sin datos en algÃºn timestamp**

In [14]:
suma = 0
for time in df.timestamp.unique(): #con groupby
    sample =  df[df.timestamp==time]
    for i in sample.columns:
        if sum(sample[i].isnull()==True):
            suma+=1
            print "columna con solo null eliminada",i
            df = df.drop(i, axis=1)
print "total eliminados ",suma

columna con solo null eliminada technical_0
columna con solo null eliminada technical_1
columna con solo null eliminada technical_3
columna con solo null eliminada technical_5
columna con solo null eliminada technical_9
columna con solo null eliminada technical_12
columna con solo null eliminada technical_16
columna con solo null eliminada technical_18
columna con solo null eliminada technical_24
columna con solo null eliminada technical_25
columna con solo null eliminada technical_28
columna con solo null eliminada technical_31
columna con solo null eliminada technical_32
columna con solo null eliminada technical_33
columna con solo null eliminada technical_37
columna con solo null eliminada technical_38
columna con solo null eliminada technical_39
columna con solo null eliminada technical_41
columna con solo null eliminada technical_42
columna con solo null eliminada technical_44
total eliminados  20

In [15]:
print df.shape #descartamos 20 columnas
print sum(df.isnull().sum())

(1710756, 91)
0

**Estandarizar caracterÃ­sticas (menos timestamp y id) de todos los timestamp al tiempo**

In [16]:
df.head(3)

,timestamp,id,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_22,technical_27,technical_29,technical_30,technical_34,technical_35,technical_36,technical_40,technical_43,y
0,0,10,0.370326,-0.006316,0.222831,-0.213030,0.729277,-0.335633,0.113292,1.621238,...,0.0,1.427469,-2.0,0.0,0.0,0.937880,0.775208,-0.414776,-2.0,-0.011753
1,0,11,0.014765,-0.038064,-0.017425,0.320652,-0.034134,0.004413,0.114285,-0.210185,...,-0.5,0.154613,0.0,0.0,0.5,0.232154,0.025590,-0.273607,-2.0,-0.001240
2,0,12,-0.010622,-0.050577,3.379575,-0.157525,-0.068550,-0.155937,1.219439,-0.764516,...,-0.5,0.378332,-2.0,0.0,-0.5,0.372688,0.151881,-0.175710,-2.0,-0.020940

In [17]:
df[:][df.columns[2:]] = (df[:][df.columns[2:]] - df[:][df.columns[2:]].mean(axis=0))/(df[:][df.columns[2:]].std(axis=0)) #divido en la media y desv de columnas
#df[:][df.columns[2:]] = (df[:][df.columns[2:]] - df[:][df.columns[2:]].mean(axis=0))/(df[:][df.columns[2:]].max()-df[:][df.columns[2:]].min()) #divido en la media y desv de columnas
#

In [18]:
df.head(3)

,timestamp,id,derived_0,derived_1,derived_2,derived_3,derived_4,fundamental_0,fundamental_1,fundamental_2,...,technical_22,technical_27,technical_29,technical_30,technical_34,technical_35,technical_36,technical_40,technical_43,y
0,0,10,0.020306,-0.01032,0.009900,0.003125,-0.021868,-1.272671,0.010149,0.549544,...,0.011904,2.229043,-1.124514,-0.44177,0.001422,1.886968,1.406403,-1.496165,-1.069776,-0.534454
1,0,11,0.018850,-0.01032,0.005693,0.008598,-0.022813,0.099876,0.010149,-0.014142,...,-1.213205,0.341856,0.944503,-0.44177,1.224912,0.608138,0.182066,-1.040825,-1.069776,-0.065244
2,0,12,0.018747,-0.01032,0.065175,0.003695,-0.022855,-0.547351,0.010149,-0.184758,...,-1.213205,0.673551,-1.124514,-0.44177,-1.222067,0.862796,0.388335,-0.725057,-1.069776,-0.944430

**ANOVA TS**

In [29]:
from scipy.stats import f_oneway

In [38]:
#samples = df.sample(n=5)

In [84]:
#df.groupby(by=['timestamp'])
#samples
#samples = pd.DataFrame()
samplests = []

In [85]:
for ts in df.timestamp.unique()[:5]:
    #samples = samples.append(df[df.timestamp==ts])
    samplests.append(df[df.timestamp==ts].y.as_matrix())

In [86]:
samplests[0]

array([ -5.34453690e-01,  -6.52441010e-02,  -9.44429576e-01,
        -7.22165465e-01,  -3.37382525e-01,   1.39260709e+00,
        -1.47799027e+00,   6.95388019e-01,  -1.24138999e+00,
         2.87447482e-01,  -9.46436375e-02,   2.23136187e+00,
        -8.57446194e-01,  -2.42125347e-01,  -2.94133961e-01,
         7.83086002e-01,  -5.85005917e-02,  -4.02374089e-01,
         1.80762398e+00,  -1.84903085e-01,  -5.14954269e-01,
         1.96129286e+00,   5.23826666e-02,  -5.49975097e-01,
        -3.17134762e+00,  -8.87025073e-02,  -5.69637716e-01,
         1.31546259e+00,   1.36539447e+00,  -7.38953233e-01,
         1.83024085e+00,  -3.85228133e+00,  -8.92170429e-01,
        -8.62213373e-01,  -1.89124346e+00,   6.78545356e-01,
        -1.18385923e+00,  -7.11004078e-01,  -1.10446133e-01,
        -5.43867350e-01,  -1.86157620e+00,   7.14548588e-01,
        -9.03721154e-01,  -1.81468055e-01,  -1.12109089e+00,
        -5.99859357e-01,   2.97105622e+00,  -1.01287104e-01,
         1.04106320e-02,  -1.06029963e+00,   1.31986812e-01,
         1.38680184e+00,  -1.56319767e-01,  -7.28181228e-02,
        -4.09318954e-01,  -5.73458493e-01,  -1.14889109e+00,
         5.21981083e-02,  -4.31266129e-01,  -2.48538017e+00,
        -2.39154007e-02,  -1.52908766e+00,   1.48401713e+00,
        -4.32224423e-01,   6.07121825e-01,  -2.95382202e-01,
        -5.86515546e-01,   1.39768517e+00,   1.49483219e-01,
        -5.39473355e-01,   1.16514027e-01,  -1.33218303e-01,
        -1.08964002e+00,   6.38073087e-01,   2.48321962e+00,
        -1.45275283e+00,   2.86017561e+00,   2.12359682e-01,
         1.44994938e+00,  -6.26967311e-01,  -3.12018871e+00,
        -9.08441097e-02,   1.80899948e-01,   6.38462663e-01,
        -8.18345070e-01,   1.06543016e+00,  -1.39942217e+00,
         3.93383712e-01,   3.67368519e-01,  -1.41896665e-01,
         1.88702130e+00,   7.76105285e-01,   2.08752155e-01,
         2.51835510e-02,   7.46078789e-01,  -5.84906898e-02,
        -3.38054270e-01,  -1.16672862e+00,   1.85773695e+00,
         3.45693618e-01,  -1.40797067e+00,   1.74722552e+00,
        -1.54757130e+00,  -6.68073833e-01,  -2.37580538e-01,
         3.28558862e-01,  -6.40155613e-01,   1.53894770e+00,
         1.91062927e-01,  -6.79199025e-02,   5.48817039e-01,
         1.38697970e+00,   6.15404725e-01,  -2.48972440e+00,
        -1.25573957e+00,   4.07700747e-01,  -2.79516410e-02,
        -4.09891933e-01,   1.22188580e+00,  -7.55174637e-01,
        -2.99441993e-01,   4.99605477e-01,  -1.31778133e+00,
         1.12841666e+00,  -6.39916480e-01,  -4.30657387e-01,
        -8.11533988e-01,   1.84676334e-01,   2.17856669e+00,
        -1.35209465e+00,   9.12797689e-01,   2.62010169e+00,
        -2.02822614e+00,  -1.69593096e+00,  -2.15351462e+00,
        -1.82846487e+00,   1.01094627e+00,  -3.75409760e-02,
         2.46318877e-01,   1.53633773e-01,  -4.09078330e-01,
        -9.47846413e-01,   6.85045481e-01,   6.07524812e-01,
        -1.13935149e+00,  -3.85228133e+00,  -1.09786367e+00,
        -5.92930019e-01,  -4.11060452e-01,   3.35555404e-01,
        -2.14989707e-01,  -1.71947628e-01,  -3.92266929e-01,
        -4.14132833e-01,   3.08963358e-01,   2.60476208e+00,
        -1.46709785e-01,  -7.79513836e-01,  -1.09191227e+00,
         8.74399900e-01,   2.23300767e+00,  -2.69744694e-01,
        -6.14885092e-01,  -7.07583904e-01,  -8.00718486e-01,
         9.05508935e-01,   2.56470561e-01,   3.95680338e-01,
        -7.39771783e-01,  -1.22328006e-01,   3.46881717e-01,
        -9.66231048e-01,  -3.29282939e-01,  -8.25497031e-01,
         1.22971797e+00,   1.26685345e+00,  -2.35433772e-01,
        -6.58759028e-02,   3.20672655e+00,  -1.39441705e+00,
        -8.72743428e-01,   8.31502795e-01,   2.59111762e-01,
        -2.08628386e-01,   6.55813739e-02,   4.08403778e+00,
         2.32373312e-01,  -1.01620883e-01,  -5.28082728e-01,
        -2.64395690e+00,  -2.36117095e-01,  -9.57156420e-01,
        -7.52990723e-01,  -3.19384933e-01,   1.31818846e-01,
         1.51046157e+00,   3.65128785e-01,   4.37959582e-01,
         4.80250381e-02,  -9.81138587e-01,   1.15595794e+00,
         3.51539999e-01,  -1.14658487e+00,  -2.88628489e-01,
        -4.19481564e-03,  -2.65030360e+00,  -2.00219095e-01,
        -4.10029776e-02,   5.20363450e-01,  -3.78026783e-01,
         5.65484725e-02,   9.47426617e-01,   1.77512205e+00,
        -2.26938891e+00,   3.39060247e-01,   6.59547806e-01,
         7.67704010e-01,  -2.42022514e-01,   4.04351830e-01,
        -7.38239437e-02,   1.03842878e+00,  -5.40863037e-01,
        -6.02830291e-01,   3.59058231e-01,   4.88566101e-01,
         7.41337299e-01,   8.41960609e-01,   2.92945981e-01,
        -1.29401886e+00,  -6.64323211e-01,  -6.44559264e-01,
         1.59872577e-01,  -1.74849957e-01,   2.87097782e-01,
         9.54244006e-03,  -2.73950219e-01,  -2.34226599e-01,
        -6.81748748e-01,   1.32260352e-01,  -2.25118136e+00,
        -6.97498322e-01,   1.44611466e+00,  -3.03220916e+00,
         1.01539278e+00,  -3.97988260e-01,  -3.06055099e-02,
         2.75306416e+00,   2.74316907e-01,  -2.57143140e-01,
        -3.38904381e-01,   2.03221989e+00,  -3.66809875e-01,
        -9.80069339e-01,   1.28514028e+00,   2.96162367e-01,
         1.07522801e-01,  -2.13707638e+00,  -1.32598445e-01,
         8.39779854e-01,  -4.04395871e-02,  -4.50456232e-01,
         1.95876673e-01,   8.92589390e-01,  -3.25591469e+00,
         1.02949297e+00,  -9.35336411e-01,  -5.61708659e-02,
        -1.12158334e+00,   1.74048975e-01,   5.79200983e-01,
        -4.08242762e-01,  -1.59722412e+00,  -1.25741621e-03,
         6.00961894e-02,   2.49771786e+00,  -1.23262537e+00,
         4.75260407e-01,  -3.63528073e-01,  -3.54311824e+00,
         5.45930378e-02,  -2.07613289e-01,  -2.76840985e-01,
         8.64171565e-01,  -1.94489568e-01,  -2.42936587e+00,
        -2.74977654e-01,  -3.59332353e-01,  -6.06934965e-01,
        -4.43015732e-02,   4.23794329e-01,   6.97689235e-01,
        -1.77093482e+00,   2.69247818e+00,  -2.05561686e+00,
         2.71259522e+00,   1.63067892e-01,  -6.76688671e-01,
         2.46191606e-01,  -9.80821013e-01,  -4.56821650e-01,
        -1.87175179e+00,  -2.48722243e-03,   1.92259777e+00,
        -1.52506602e+00,   1.75960350e-03,  -1.49575043e+00,
        -1.47630334e+00,   2.79096317e+00,  -1.79680860e+00,
         2.23327541e+00,  -4.73059297e-01,  -4.82495010e-01,
         3.33779186e-01,   2.54818708e-01,  -1.46486390e+00,
        -5.83067477e-01,   5.31569839e-01,   5.80778956e-01,
        -7.05295920e-01,   1.47941327e+00,   1.19297457e+00,
        -9.02837738e-02,   2.30851993e-01,  -3.25484052e-02,
        -1.55437386e+00,   6.75930202e-01,  -9.83467042e-01,
        -5.74217021e-01,   8.71810541e-02,   3.09936285e-01,
        -4.78384435e-01,   7.01974213e-01,   8.95454466e-01,
         1.96158695e+00,  -2.19085783e-01,  -6.67019784e-01,
         2.63186008e-01,   2.50692725e+00,  -1.41638279e+00,
        -3.85228133e+00,   7.78934121e-01,   3.41561198e-01,
         9.08468306e-01,  -2.10059142e+00,   6.16536856e-01,
        -3.59195054e-01,  -1.69387412e+00,  -1.82731986e+00,
         3.06833982e-01,   1.12563360e+00,  -6.58852577e-01,
        -1.35746324e+00,   1.49153841e+00,  -1.96212038e-01,
         5.06782532e-01,  -3.46054769e+00,  -1.57038853e-01,
         1.46985412e+00,   1.30774033e+00,  -2.39743209e+00,
        -7.23534942e-01,  -2.29524344e-01,   1.60933197e-01,
         1.01659262e+00,  -9.03955102e-01,  -1.53123006e-01,
        -3.51270109e-01,   2.00554585e+00,   1.70065820e+00,
        -1.95407301e-01,  -3.65622115e+00,  -7.53085613e-01,
        -1.48343578e-01,   9.33337286e-02,   9.49229419e-01,
        -4.75308955e-01,  -1.73717356e+00,  -1.10144806e+00,
         3.82412243e+00,   4.38057572e-01,  -1.73847377e-01,
         1.82404506e+00,   1.69333422e+00,   9.39701617e-01,
        -1.02857471e+00,  -5.03278039e-02,   5.40474415e-01,
         2.17407644e-01,   6.98225021e-01,  -1.63757241e+00,
        -5.42404532e-01,  -7.46183619e-02,  -1.14428568e+00,
         2.82980978e-01,  -1.35807451e-02,  -2.17623973e+00,
        -7.70960212e-01,  -1.82865158e-01,  -3.33573961e+00,
         1.25434744e+00,  -2.60333687e-01,  -8.88649285e-01,
        -5.18638939e-02,   1.68176129e-01,   7.50498056e-01,
        -2.78306007e+00,  -8.52026641e-01,   2.51229835e+00,
        -1.70471549e-01,  -7.24730939e-02,   3.29651475e-01,
         3.82636756e-01,  -8.77915800e-01,   2.09894967e+00,
        -8.06708515e-01,  -5.97720623e-01,  -1.08094335e+00,
         8.51483941e-01,  -1.14767206e+00,  -2.89699888e+00,
        -9.74819779e-01,  -2.70207858e+00,  -4.71600354e-01,
        -1.15659542e-01,   4.04545397e-01,   2.24879551e+00,
         2.93739128e+00,  -2.91232824e+00,  -1.67449370e-01,
         7.75611877e-01,   1.03826177e+00,  -7.50847876e-01,
        -5.39064825e-01,  -5.35396218e-01,   7.00203419e-01,
         1.72038078e-02,   1.23320651e+00,  -5.95100880e-01,
        -3.27955306e-01,  -5.59257329e-01,  -1.51182979e-01,
        -5.36076307e-01,  -1.04476452e+00,  -5.74777365e-01,
        -5.51359713e-01,   1.36342847e+00,  -8.18327248e-01,
        -6.73317388e-02,   1.04136482e-01,   1.34060442e-01,
         3.81847352e-01,  -7.16220081e-01,  -7.35445559e-01,
         7.54563034e-01,  -8.07882667e-01,  -3.32506180e-01,
        -6.14164889e-01,   2.59327978e-01,  -4.53011960e-01,
         6.00322008e-01,  -4.91640866e-01,  -1.33124843e-01,
         1.46243501e+00,  -1.11012161e+00,  -7.01528132e-01,
        -1.48054704e-01,  -5.95156491e-01,   1.40804434e+00,
        -1.14215481e+00,   1.20493746e+00,  -1.04367292e+00,
        -6.46315336e-01,  -1.36761665e-01,  -1.55190930e-01,
        -1.08010972e+00,   7.79842973e-01,   5.82098901e-01,
         9.19319212e-01,   5.26643336e-01,  -2.12049270e+00,
         1.08555090e+00,   7.03806698e-01,  -3.24374348e-01,
        -1.14598227e+00,  -1.40218949e+00,  -1.20467174e+00,
        -8.64154220e-01,   2.54967600e-01,  -5.06237268e-01,
         7.74666429e-01,   5.41813135e-01,  -9.72922072e-02,
         1.07667536e-01,   8.36301818e-02,   1.02026129e+00,
         6.26989305e-01,  -2.56151319e+00,  -2.22521603e-01,
        -6.02506697e-01,  -8.46908927e-01,  -1.54912663e+00,
        -2.74090827e-01,  -1.61265671e+00,   8.15721273e-01,
        -1.46543786e-01,  -4.52782959e-01,  -1.87591150e-01,
         1.79414880e+00,  -6.73805058e-01,  -2.61266261e-01,
        -2.25921535e+00,   6.25742897e-02,   2.38494587e+00,
        -1.95383295e-01,  -1.87840253e-01,   8.62235904e-01,
        -1.11875318e-01,   2.67136008e-01,   4.49654341e-01,
        -1.27301380e-01,  -1.67500775e-03,  -1.46914315e+00,
         5.41326761e-01,   7.46696770e-01,   9.89304602e-01,
         3.72255296e-01,  -8.60989213e-01,   1.10154831e+00,
         9.67578471e-01,   6.28987670e-01,  -6.85724854e-01,
        -2.75557518e-01,   3.73003036e-01,  -9.19385970e-01,
         1.24360606e-01,  -2.90557295e-01,  -3.79814291e+00,
        -3.80736023e-01,  -1.83777288e-01,  -8.17647297e-03,
         2.33691230e-01,  -9.45705116e-01,  -3.85228133e+00,
         5.52603066e-01,  -3.20780128e-01,  -3.10604066e-01,
        -5.76218069e-01,  -1.01118870e-01,  -4.78219509e-01,
         4.72968340e-01,  -6.74441457e-02,   1.79587007e-02,
         3.97489905e-01,   4.17726249e-01,  -2.20516014e+00,
         2.81231035e-03,  -7.17513025e-01,   2.79404670e-01,
        -3.99314433e-01,  -2.70547926e-01,  -1.26874614e+00,
         2.11112237e+00,  -1.54580027e-01,   2.01574922e+00,
         4.37972277e-01,   6.17943145e-02,   2.25127503e-01,
         1.67491961e+00,  -1.54680407e+00,  -5.53711891e-01,
        -9.59315240e-01,   2.14158273e+00,  -6.48001194e-01,
        -4.16683555e-01,  -3.85228133e+00,  -2.94194889e+00,
         4.06487256e-01,  -1.28656864e+00,   1.31298733e+00,
        -1.31079662e+00,   8.12322676e-01,  -6.07722640e-01,
         1.09276753e-02,  -8.21597338e-01,   2.33150172e+00,
        -6.96341038e-01,   2.62982035e+00,   1.14048265e-01,
        -1.45985350e-01,   1.11063206e+00,   1.40204942e+00,
         1.42686069e-01,   7.65539646e-01,   2.73581958e+00,
         7.92501509e-01,  -1.02169895e+00,  -3.19128186e-01,
        -9.99546289e-01,  -2.31177673e-01,   4.21528250e-01,
        -1.45892352e-01,   4.94376719e-01,   9.43352878e-01,
         1.52637521e-02,   1.73650765e+00,   1.25076890e-01,
         8.79756451e-01,   1.21708643e+00,   1.70430398e+00,
        -1.16562210e-01,   1.43893647e+00,   5.19823909e-01,
        -7.98783302e-01,  -1.86527467e+00,  -2.58438379e-01,
         7.59497657e-02,   1.50439546e-01,   1.10223436e+00,
         3.05462313e+00,  -1.89334893e+00,  -1.36158526e+00,
         1.89521849e-01,  -6.02325022e-01,   8.56631041e-01,
        -8.23295534e-01,  -7.24056900e-01,  -3.89746338e-01,
        -1.12356555e+00,  -1.42503631e+00,   9.55642223e-01,
        -9.00626063e-01,  -2.57490486e-01,  -1.95471013e+00,
        -7.29318336e-02,  -1.49702513e+00,   1.35926914e+00,
        -5.07569671e-01,  -2.39663213e-01,  -3.73280674e-01,
         5.47546148e-01,   1.21186063e-01,  -7.32875586e-01,
        -1.29454751e-02,   8.76558363e-01,  -9.75459874e-01,
        -8.34343553e-01,  -7.37418830e-01,   1.44140637e+00,
        -5.22470176e-01,  -5.41638374e-01,   1.38379085e+00,
        -5.47127761e-02,   9.09202576e-01,  -6.02325320e-01,
        -1.19533920e+00,   3.32782596e-01,  -4.10465777e-01,
         9.98879150e-02,   4.27234858e-01,  -4.00945157e-01,
         1.72177419e-01,  -3.03379089e-01,  -3.31080973e-01,
         1.94285035e+00,  -9.15245861e-02,  -9.07987475e-01,
        -2.76260730e-02,  -2.24273324e-01,   1.28652775e+00,
        -1.37943089e+00,   2.24326365e-02,   3.04830372e-01,
        -1.46614575e+00,  -5.18368967e-02,  -5.80020070e-01,
         2.94928044e-01,  -9.01421726e-01,   5.02852142e-01,
         5.44635542e-02,   1.70429790e+00,  -7.66367137e-01,
         1.01598728e+00,   1.26456547e+00,  -3.62048030e-01,
        -6.61646962e-01,  -6.31565571e-01,   1.53891933e+00,
        -7.01946735e-01,   4.05629969e+00,  -1.27704072e+00,
         1.67876959e+00,   2.67545462e+00,  -4.00228828e-01,
        -6.69006288e-01,  -1.35870504e+00,   7.02018261e-01,
        -4.06793147e-01,  -3.30931634e-01,  -3.93015504e-01,
         2.68645716e+00,  -3.85228133e+00,  -1.03162360e+00,
         3.45420271e-01,  -2.23187163e-01,  -6.14561558e-01,
        -1.40845120e-01,  -2.32232022e+00,  -1.85132712e-01,
         7.85236299e-01,   1.35693818e-01,  -3.76347828e+00,
        -1.06896043e-01,  -5.79907358e-01,  -3.76662523e-01,
        -1.53450179e+00,   1.04796791e+00,   1.83395157e-03,
        -1.17207921e+00,  -6.80906415e-01,   1.06926918e+00,
         2.19268218e-01,   3.83225083e-01,   1.01972258e+00,
         1.45148247e-01,  -4.30003583e-01,   1.65362036e+00,
        -1.42316550e-01,   1.01150405e+00,   1.17611535e-01,
         9.56353903e-01,   2.37787649e-01,  -5.64172864e-01,
         4.91557121e-01,  -2.54633993e-01,   2.06856585e+00,
        -3.65555197e-01,  -2.93483329e+00,  -6.24080062e-01,
        -7.39215553e-01,   4.67874855e-01,  -1.07329994e-01,
        -4.30385590e-01,   5.26446819e-01,   8.33322555e-02,
         2.36712480e+00,  -6.80472195e-01,  -7.38947153e-01,
         6.64753616e-01,  -7.30724990e-01,  -5.33073127e-01], dtype=float32)

In [87]:
f_oneway(samplests[0],samplests[1],samplests[2],samplests[3],samplests[4])

F_onewayResult(statistic=8.5160626582870584, pvalue=7.7413004156383505e-07)

**ANOVA ID**

In [88]:
samplesid = []
for i in df.id.unique()[:5]:
    #samples = samples.append(df[df.timestamp==ts])
    samplesid.append(df[df.id==i].y.as_matrix())

In [89]:
samplesid[0]#.as_matrix()

array([-0.53445369,  0.25119597, -0.03116127,  0.22273117, -3.45580649,
        0.2617051 , -1.24824452, -1.49623394, -0.10962389,  2.98345923,
       -0.25039294, -0.53061014, -1.31423187,  0.03862358, -0.24239188,
       -3.85228133, -3.06382537,  0.19261484,  1.87552321,  0.12992688,
        0.21797955, -3.13913035, -0.66443038, -1.03586686, -0.098992  ,
        0.28115329, -0.66103184,  0.61547631, -0.06126763, -0.99706399,
        0.38430983, -1.09696555, -0.43917075,  1.77200496, -0.73140508,
        0.93185633,  1.29878426, -0.34819779,  0.35927171,  0.64684981,
        0.055293  , -0.36492807,  1.18890989, -0.59127986, -0.25394568,
       -0.05845671,  1.24515927,  1.0312525 ,  0.66192329, -0.15286018,
        0.34626102, -0.16163689, -0.27919489,  0.08777264, -0.98314351,
       -0.7206825 ,  1.62263286, -0.43058717,  4.16291428, -1.63317716,
        1.32534933, -1.0070169 , -0.37667599, -0.48266217,  2.3401463 ,
        1.22679806,  0.44349104, -0.30804861,  0.36254013,  1.77835011,
       -0.19104789,  0.40518972,  0.00564093, -0.15495448, -0.83654302,
       -0.00903175,  0.82269192,  0.29015163,  1.21827948, -0.33776686,
        0.28076029, -0.52979863, -0.41719148,  1.0895654 , -0.37017012,
       -0.20744321, -3.85228133,  1.39878607,  0.27704322, -0.31585076,
        0.49395844, -0.39960414,  0.3315255 , -0.14991237, -1.38108981,
        0.2657336 , -0.24239852, -0.50475085,  0.59183937,  0.65992546,
       -0.09845854,  1.29174197,  0.14699289,  0.63863927, -0.88451415,
       -0.41668636, -0.32585934, -0.3201353 , -0.70225126, -2.09423733,
       -0.17467353, -1.41067588,  1.13555455,  4.16291428,  0.02398842,
       -1.22139513], dtype=float32)

In [90]:
f_oneway(samplesid[0],samplesid[1],samplesid[2],samplesid[3],samplesid[4])

F_onewayResult(statistic=0.54662387653482447, pvalue=0.70150748362481841)

### ConclusiÃ³n 

Valor P: Se busca que sea < 0.05, es una distribuciÃ³n F. P indica que tan significativa ees la diferencia en los tratamientos (5 muestras). Usamos timestamp y id y vemos que hay mÃ¡s diferencia significativas entre los timestamps.

from multiprocessing import Pool

#df = df.apply(lambda x: x.fillna(x.mean()),axis=1)
group = df.groupby(by=["timestamp"])